# configuration file for production environment

# database driver and location of the is/are databases
dbm_driver: "AnyDBM_File"
dbm_basename: "/srv/www/purl/html/Prospero/Prospero"

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1
