# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "App::Factoid::Browser"

# Tell Dancer we're behind a proxy
behind_proxy: "true"

# Return objects instead of hash references when 'config' is queried
strict_config: "true"

# What environment are we running under?
#environment: "production"
#environment: "development"

# How to serialize data?
serialization: "JSON"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"
# changes layout, layout points to new stylesheet 'miranda.css'
layout: "miranda"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

